version: '3.1'

volumes:
    cache:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33
    logs:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: uid=33

services:
  application:
    image: hackzilla/elastic-talk
    container_name: application
    build: .
    volumes:
      - ./code:/var/www/html
      - cache:/var/www/html/var/cache
      - logs:/var/www/vhtml/ar/logs
      - ./secrets:/run/secrets
    environment:
      MYSQL_DATABASE: 'symfony'
      # Shouldn't be using root here
      MYSQL_USER: 'root'
      MYSQL_PASS: 'test_pass'
#      MYSQL_USER: 'test'
#      MYSQL_PASS: 'pass'
    links:
      - database
      - elastic
#    depends_on:
#      database:
#        condition: service_healthy
    ports:
      - 8888:80
  elastic:
    image: hackzilla:elastic-agent
    container_name: elastic
    environment:
      - cluster.name=docker-cluster
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      # TODO: Change this
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_DATABASE: 'symfony'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./data/database:/var/lib/mysql
    healthcheck:
      interval: 1s
      timeout: 5s
      test: nc -z localhost 3306"
      retries: 5
    ports:
      - 3307:3306

