# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    register_impression:
        class: AppBundle\Service\RegisterImpression
        arguments: ['@doctrine.orm.entity_manager']

    routes:
        class: AppBundle\Service\Route
