# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    register_impression:
        class: AppBundle\Service\RegisterImpression
        arguments: ['@request_stack', '@doctrine.orm.entity_manager']

    routes:
        class: AppBundle\Service\Route

    app.impression_indexer_listener:
        class: AppBundle\EventListener\ImpressionIndexerSubscriber
        arguments:
            - '@app.elastic'
            - '%elastic_index%'
            - '%elastic_type%'
        tags:
            - { name: doctrine.event_subscriber }

    app.elastic:
        class: AppBundle\Service\Elastic
        arguments:
            - '%elastic_host%'
            - '%elastic_port%'
